### ISSUE TITLE
How to deep link to council sites if we only have a council domain?

### ISSUE THREAD

**Issue by mrchrisadams** [mysociety/caps#101]
Hi there,

I'm writing this as an issue for some pointers on how best to deep-link to content on your site, from the own green checking service we make use ourselves in the green web green check tool at the link below:

https://www.thegreenwebfoundation.org/green-web-check

We currently work by doing a DNS look up on a domain, and then finding some information, about the corresponding IP range in use for a given site.

So, for a site like cloudflare in addition to marking it as green, we point to the underlying credentials and any information we have in the context of climate.

See an example below, where we point to their own comms information, and also the numbers and evidence base they are sharing publicly:

https://www.thegreenwebfoundation.org/green-web-check/?url=cloudflare.com

### Doing something like this for public bodies as well as private companies:

We're looking at being able to do something like this, but extend our ability to return information for a "green check" so instead of just showing that hackney is using google as a host, we can check the domain against a list of entities and show richer information.

So for example, any domain that was subdomain of hackney.gov.uk:

https://www.thegreenwebfoundation.org/green-web-check/?url=hackney.gov.uk

We'd be able to also link to this page here:

https://data.climateemergency.uk/councils/london-borough-of-hackney/

We're aiming to define a convention for organisations to disclose information at a domain level called carbon.txt, that can be consumed by anything using our API - we are serving around 7-8 million API requests per day at present, and experimenting with making the data in our API responses richer to people think more holistically about climate action.

But until we have that sorted out, we're looking to rely on some kind of mapping between a domain, and  a useful url to present for users.

### How I think it might work

I see in issue #7  that there that has a list of council website urls, that we could use as a starting point.

It would be really cool to be able to go from: `hackney.gov.uk` 

To an address like this:

https://data.climateemergency.uk/councils/london-borough-of-hackney/

I _can_ see the a link back to hackney there on the https://data.climateemergency.uk page, and this makes me think it might be possible to expose a lookup table.

If that existed, given a council domain as a key, I think we'd be able to link to the relevant page, but I can't see how to generate it without some pointers from someone at Mysociety who knows the data better.

Would something like sharing a JSON or CSV representation of a query along these lines work?

```python
[
  (council.website_url, council.get_absolute_url() )
  for council 
  in Council.objects.all()
]

```

I'm basing that code on reading the Council model at the url below:

https://github.com/mysociety/caps/blob/master/caps/models.py#L19-L69

### Some other background

I'm a big fan of this project - I spoke about why I think it's important, and a good example of using technology to help engage on a societal level at Djangocon EU this year.

The videos of the talk is now on youtube, and the talk is a bit long, so I've just linked to the specific bits on youtube mentioning mysociety and caps:

The first mention of caps and mysociety's work around climate action plans (2-3 mins)
https://youtu.be/quLFLH36Lro?t=1610

The second mention and a call to action around caps (2-3 mins):
https://youtu.be/quLFLH36Lro?t=2821

There's more at the link below, including the entire deck I used if you want to link to any of it:
https://www.thegreenwebfoundation.org/djangocon-eu-2021/

**Comment by struan** [comment]
Thanks for the detailed ticket. We're going to aim to get this done fairly soon.

**Comment by struan** [comment]
Hi @mrchrisadams,

we've added the very basics of an API to the site at https://data.climateemergency.uk/api/. There's only one end point at the moment which is a list of council data.

Happy to hear any feedback on it, or extra data that might be useful to include.

**Comment by mrchrisadams** [comment]
HAHAH! YES, NICE ONE @struan!

This is great, there's enough here so that any for look up on localcouncil, we can point to some substantial information about the climate response and how to engage on this too.

```json
    {
        "name": "London Borough of Hackney",
        "url": "/councils/london-borough-of-hackney/",
        "website_url": "http://www.hackney.gov.uk/",
        "gss_code": "E09000012",
        "country": "England",
        "authority_type": "London Borough",
        "plan_count": 1
    },
```


And presumably, anything that subdomains of the main part like  `*.hackney.gov.uk` we might plausiby be able to link back to the plans information too.

I only choose hackney as an example here - there's loads going on that I'm a big fan of climate wise. 

If anything comes up, I'll raise an issue, but you've made my day with this - thanks 👍
