### ISSUE TITLE
Long council names break the line

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/caps#113]
![image (15)](https://user-images.githubusercontent.com/944656/130967994-9fb1bbca-900f-4b24-a26a-2dbeba2fef44.png)

**Comment by zarino** [comment]
Happens a lot at the akward middle widths – not quite phone sized, but not quite full desktop.

Gets crazy when the council name has multiple long words in it:

<img width="317" alt="Screenshot 2021-09-01 at 11 46 04" src="https://user-images.githubusercontent.com/739624/131658604-8bb1435b-d534-4a5e-814f-33f01a84b69a.png">
