### ISSUE TITLE
Show people how to cite / reference the data on our site

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#115]
In a discussion about tracking our academic impact, @crowbot suggested:

> we could add a request that people let us know if they use the site in policy or research work and maybe include a format for how to cite it [and then use google alerts to track usage]

For some reason I thought we had a message like this on the TheyWorkForYou MP pages, but it appears not. Maybe I’m thinking of the Hansard citations on the debate pages.

Anyway @ajparsons do you have any ideas on what wording journlists / researchers should use when citing the data they find on our site?

**Comment by ajparsons** [comment]
The research sites have a suggested citation way down the bottom. https://research.mysociety.org/publications/reforming-foi

From their point of view, it needs to remind them that they can cite websites and make it easy to do so. So for people who will create hyperlinks, make it easy to grab the URL. For academics, given them a basic format, they won't use it exactly, but it has the building blocks of how we'd like them to:

>mySociety, Climate Emergency (2021). Climate Action Plan Explorer: Allerdale Borough Council. Available at: https://data.climateemergency.uk/councils/allerdale-borough-council/ [Accessed 1 Sep 2021].


From our point of view, this is an opportunity to make sure people use whichever URL we'd prefer to share and the format of words we'd like to use in citation for google scholar alerts > "Climate Action Plan Explorer". (or whatever distinct and unique phrase we go with).

**Comment by zarino** [comment]
Noting for future me – [the `{% now %}` template tag](https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#now) will get us the current date
