### ISSUE TITLE
Export dummy/incomplete version of scoring information

### ISSUE THREAD

**Issue by ajparsons** [mysociety/caps#119]
So development can start on integration of scores, need an idea of what the output of the plan scoring process will look like. 

Weights are currently unknown, but need to be able to account for them.

This ticket will produce for a council:

1) overall score for a council
2) how that overall score breaks down into each (weighted) category – so we can show how much each category has contributed to the overall score, eg, in a stacked bar chart or pie chart
3) the “raw” (unweighted) category scores – so we can display each of them in isolation, eg, in their own little bar chart
4) A file with more information on the individual questions. (like rti rating)

**Comment by ajparsons** [comment]
This file should provide was is needed. It has scores for each section for each council (many of which are currently blank), the total number of points available for a section, and an overall score section. This is weighted by the relative weight for each section (currently '1' for all). 

https://github.com/mysociety/caps_plan_processing/blob/main/data/section_scores_by_council.csv

**Comment by ajparsons** [comment]
@zarino @struan : 

This file should provide was is needed. It has scores for each section for each council (many of which are currently blank), the total number of points available for a section, and an overall score section. This is weighted by the relative weight for each section (currently '1' for all). 

https://github.com/mysociety/caps_plan_processing/blob/main/data/section_scores_by_council.csv

**Comment by struan** [comment]
This looks pretty reasonable. I need to think about how I'm going to import this to work out if there's anything else I need/would make things easier.

How will the weightings work for adding up the final score?

**Comment by ajparsons** [comment]
Unclear as of yet, it's just been talked about so I put a dummy step in that doesn't do anything yet.

The main effect of weighting would be to adjust the raw score and total number of points possible for the overall score. So it is probably best to convert to percentages before grade bounds are applied as that will keep everything consistent.
