### ISSUE TITLE
Display Northern Irish councils as their own authority type (not Unitary)

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#134]
Northern Irish councils are currently modelled as Unitary Authorities. That matches with how, say, [the Institute for Government describes them](https://www.instituteforgovernment.org.uk/explainers/local-government).

But they’re not _technically_ Unitaries, and they have far fewer powers/responsibilities than Unitaries elsewhere in the UK.

[Wikipedia calls them "District Councils".](https://en.wikipedia.org/wiki/Local_government_in_Northern_Ireland)

[MapIt calls them "Northern Irish Councils".](https://mapit.mysociety.org/areas/LGD.html)

We should be consistent on how we describe them. Any thoughts @struan @ajparsons ?

**Comment by ajparsons** [comment]
My [lookup datasheet](https://github.com/ajparsons/uk_local_authority_names_and_codes/blob/master/uk_local_authorities.csv) also says District, and that originally inherits from the (former) register of local authorities, so that seems a good path to go down.

**Comment by zarino** [comment]
Given the Scorecards site handles Northern Irish councils as an `authority_type` of their own, I’m wondering whether it’d be less misleading to present Northern Irish councils as their own "Authority type" in CAPE too:

<img width="395" alt="Screenshot 2022-02-17 at 11 42 08" src="https://user-images.githubusercontent.com/739624/154474600-ded97490-86ea-49ee-96ba-fabf04dc9418.png">
