### ISSUE TITLE
add climate promises data to the API

### ISSUE THREAD

**Issue by struan** [mysociety/caps#147]
Also make available via a CSV.

I think the CSV should be a separate thing to the existing one, largely because they don't map very well and it'd be confusing.

Also, I think we probably need to think about adding a "here is our data" page which explains all this.

**Comment by zarino** [comment]
>  add climate promises data to the API

Promises ("commitments") were added to the API and CSV file dumps, by #150.

> adding a "here is our data" page which explains all this

The `/about/data` page was added by #153.
