### ISSUE TITLE
add a page explaining what data we have

### ISSUE THREAD

**Issue by struan** [mysociety/caps#148]
As we make more data available we should have a page which explains it.

It should list:
 * What data is available
 * a bit about how the data is structured
 * how to use it?
 * where it's sourced from

**Comment by zarino** [comment]
@struan I think this has been covered by https://github.com/mysociety/caps/pull/153. Is there anything else you think we’re missing from that page?

**Comment by struan** [comment]
I don't think so. Plus I assume we will add to this page as we add more data.
