### ISSUE TITLE
Unexpected Solr stemming results in, eg: "expenses" (in quotes) returning results for "expensive"

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#168]
There’s probably nothing we can do about overzealous stemming for queries like `expenses` returning results for `expens*`, but I think most people would expect, when they put double quotes around their search term, it should return only _exact_ phrase matches.

Yet, a search for `"expenses"` (https://data.climateemergency.uk/search/?q=%22expenses%22) still includes results for words other than `expenses`.

Is this something we can tweak in the Solr setup?

**Comment by struan** [comment]
Fixed in #170
