### ISSUE TITLE
[CCL] Header, footer, and base styles and markup

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#176]
- [x] Use Bootstrap
- [x] Nav bar with menu items and a search box
- [x] Footer with CE UK branding (@lucascumsille)

### Related

#177 – Header search box

**Comment by lucascumsille** [comment]
- [ ] Change font-size H3 on mobile to 18px (@lucascumsille)
- [ ]  Change font-size body to 13px-15px (@lucascumsille)
