### ISSUE TITLE
[CCL] Homepage: Introductory text

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#180]
- [x] Text to display at the top of the homepage(s) setting some context, and linking to another page (about/methodology?) for more (@lucascumsille)
- [x] Wording needed from @MyfanwyNixon and CE UK

**Comment by MyfanwyNixon** [comment]
This might be helpful - was in the intro for the activists' guide, but has been cut with a note that it should be on the website instead.

>[The Climate League is] an assessment of every UK council's Climate Action Plan, scoring them across nine essential areas of their strategy for transitioning to zero carbon.
>Want to know more? There are details on the methodology used to create the Climate Action Plan league [here].
The project is led by the charity Climate Emergency UK, with technical support from mySociety.
