### ISSUE TITLE
[CCL] Ability to display a council score as “in review”

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#201]
- [ ] Field on Council model to mark a council as "in review" (@struan)
 - [x] Display prominent message on Council page to explain that the data on the page is currently under review (@lucascumsille / @struan)
 - [ ] Display a small icon (warning triangle? positioned similarly to the "top performer" stars?) anywhere else the council’s name appears in the other tables (@lucascumsille / @struan)

**Comment by MyfanwyNixon** [comment]
I did think this when I proofed the copy, but I think it even more now I see it in situ:
>Our small team is currently reviewing this Scorecard at the request of the council.

'small' comes across as making an excuse before it's asked for. 'We are currently reviewing' reads much better.

**Comment by lucascumsille** [comment]
@MyfanwyNixon I got the same vibe.  This change will be on my next pull request. =)

**Comment by zarino** [comment]
We don’t have a field on the council/plan model for this yet – will implement it as soon as we actually _need_ to mark a council in review.
