### ISSUE TITLE
Rename repo to cape, update README and related docs

### ISSUE THREAD

**Issue by pmackay** [mysociety/caps#212]
Looks like the tool is now being referred to as Climate Action Plans Explorer, would be nice to make that consistent naming across the project?

**Comment by zarino** [comment]
Related: [#400 Does the site need a new name?](https://github.com/mysociety/caps/issues/400)

**Comment by ajparsons** [comment]
From previous renaming project experience, I think we can just do this and github's redirects work fine until we recreate a mysociety/caps. Possibly for curating a collection of caps.

**Comment by zarino** [comment]
@struan @alexander-griffen – once we’ve renamed the repo, do you think we should rename the `caps` Django app as well, to avoid confusion? Seems like [renaming a Django app is pretty involved](https://stackoverflow.com/questions/8408046/how-to-change-the-name-of-a-django-app).

**Comment by ajparsons** [comment]
I *think* the second comment there suggests a half approach, where you set a config for a `cape` app like:

```
class CapeConfig(AppConfig):
    label = 'caps'
    verbose_name = "Cape"
```

Because django derives the database name from the app label, that should prevent the need to do database changes as well as code changes.

**Comment by ajparsons** [comment]
https://github.com/mysociety/caps/pull/456 demonstrates that approach seems to work in principle. (Internally, django sees it as 'caps', but folder renamed).

**Comment by alexander-griffen** [comment]
Would this create confusion in the future if anything ever needs to be  accessed internally?

**Comment by ajparsons** [comment]
Tbh, we have a lot of projects that have strange internal names for things or databases. It wouldn't be terrible not to change it at all, but that seems like a halfway approach (which, might in certain situations, be confusing!).

**Comment by struan** [comment]
This seems like an excellent way to introduce bugs and cause ourselves a lot of pain for very limited gain.

**Comment by ajparsons** [comment]
In which case, just renaming the github repo and making a handful of readme changes would probably be enough for clarity that this is indeed the repo for the website 'cape'?

**Comment by zarino** [comment]
> In which case, just renaming the github repo and making a handful of readme changes would probably be enough for clarity that this is indeed the repo for the website 'cape'?

Yeah, that’s what I’m now thinking. I guess it’s not unusual for Django apps to be oddly named, and I doubt people will care that much if the app is called `caps` while the repo is called `cape`. But from an external consistency point of view, having a site called "CAPE" at the domain `cape.mysociety.org` running code from a repo at `github.com/mysociety/cape` does feel neat and tidy 👍

**Comment by struan** [comment]
I suspect there's also some sysadmin things to do but not too many as part of this.

**Comment by zarino** [comment]
Noted by @ajparsons in #460:

> May be a sequencing thing, but if also updating the mysociety repo, need to adjust the bottom of https://github.com/mysociety/caps/blob/master/.github/workflows/mirror.yml

**Comment by zarino** [comment]
So I think this is the plan of action:

- Rename repo to "cape" in https://github.com/mysociety/caps/settings
- Rename git.mysociety.org mirror ??
- Update documentation in README.md
- Update URL in mysociety vhost deployment script ??
- Update URL in https://github.com/mysociety/caps/blob/master/.github/workflows/mirror.yml
- Notify team members, so they can update the git remote URLs in their local repos

I’ve appended ‘??’ to the items I _think_ need to happen but wouldn’t know how to implement myself!

@sagepe @struan @ajparsons does that seem about right? Anything we’re missing?

**Comment by zarino** [comment]
CAPE now lives at https://cape.mysociety.org (rather than https://data.climateemergency.uk) which is the big public-facing change we wanted to make.

_Theoretically_ renaming the Github repo should be a simple change (and Github should handle redirects etc) _but_ if our aim is full consistency, we’d also want to change"caps" to "cape" in lots of other places (see above) and that, right now, feels like a load of work we really don’t need to do.

Closing this ticket for now. If the caps/cape inconsistency annoys us again in future, we can always re-open.
