### ISSUE TITLE
GLA needs to be added to CAPE

### ISSUE THREAD

**Issue by ajparsons** [mysociety/caps#251]
GLA plan is marked but GLA is not currently in the main cape database.

It needs to be added (just in general), but also so scorecard import can correctly load the GLA score.

**Comment by ajparsons** [comment]
Adding it to the plan sheet gets it into the database:

![image](https://user-images.githubusercontent.com/8157058/149557197-5943d1c3-6124-4e85-8f8a-ebfd7bd48a3a.png)

Problems are then: 

1. Set for moment to combined authority - but might not be the best description. 
2. Needs details added on climate emergency declaration.

**Comment by ajparsons** [comment]
GLA listed on relevant spreadsheets.

**Comment by zarino** [comment]
I think this has been done now – https://data.climateemergency.uk/councils/greater-london-authority/

(Re-open if I’ve missed something!)
