### ISSUE TITLE
Clarify wording around “social housing” powers/responsibilities

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#312]
Comment from an officer at North Herts Council:

> [CAPE] states that ‘North Hertfordshire District Council is a Non-Metropolitan District, with powers over: Social Housing’.
> 
> However we as a Council do not own any social housing stock and therefore this is not something we have powers over in this sense.
> 
> Please could the web page be updated to reflect this?

The page in question currently looks like this:

<img width="402" alt="Screenshot 2022-02-01 at 11 29 49" src="https://user-images.githubusercontent.com/739624/151960940-341ec10d-0f11-4de5-921e-dab7a09d1f8a.png">

I wonder whether a simple fix might be to rename the "Social housing" category to just "Housing" – since even councils who outsource all of their social housing responsibilities to third parties _still_ have a number of powers over "housing" in the more general sense, and any of these powers will have an effect on their carbon emissions.

@crowbot  @ajparsons would you have any issues with us using "Housing" as a title here, instead of "Social housing"?

**Comment by ajparsons** [comment]
Two ways of doing this:

There's nothing wrong with the current wording as such, could just have a prefix of "When a council owns councils housing".

More generally, we could expand to `housing`, and add some text about regulation of energy efficiency standards in social and private rented sector.

Would favour 1, and then do 2 in the long run?
