### ISSUE TITLE
[CCL] Question page: Show how councils of a given authority_type scored on the given question

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#319]
Here’s how it looked in the mockups:
<img width="871" alt="Screenshot 2022-02-03 at 14 48 39" src="https://user-images.githubusercontent.com/739624/152366077-53e09ed5-4a79-4795-868e-0c05ac4bb3e9.png">

(Note the list of councils, with a column for the council name, and a column for their score on this question out of the maximum possible score for that question … and then the `authority_type` filter buttons along the top)

Once we’ve got the table on the page, it should be _fairly simple_ to make the "jump to" functionality work via an autocomplete on the search box, just like it does on the homepage.

**Comment by struan** [comment]
Fixed by #321 (although not the search bit which we've skipped)
