### ISSUE TITLE
CAPE emissions calculations for Combined Authorities are wrong

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#323]
We’re calculating Combined Authority emissions totals incorrectly.

Eg: The "13.3 tCO2e per capita" we display [on North of Tyne Combined Authority’s CAPE page](https://data.climateemergency.uk/councils/north-of-tyne-combined-authority/) is wrong.

Looking at the BEIS subset data sheet, our 13.3 tonne figure appears to be the sum of the per-capita figures for the three constituent local authorities…

    ( 3.98 + 3.97 + 5.37 ) = 13.32 tonnes

…when it should really be the total emissions for the three authorities divided by the total population of the three authorities…

    ( 1205.3 + 825.3 + 1730.4 ) / ( 302820 + 207913 + 322434 ) = 0.0045 kilotonnes = 4.5 tonnes

I think the same bug is also present in the "20.5 ktCO2e per km<sup>2</sup>" figure – looks to me like a sum of the constituent local authorities’ figures, rather than total emissions divided by total area.

Also, while we’re at it – are we sure these figures are really about CO<sub>2</sub> _equivalent_? The BEIS spreadsheet only mentions CO<sub>2</sub>.

**Comment by zarino** [comment]
@struan @ajparsons I’d appreciate your thoughts on this – could be I’ve got entirely the wrong end of the stick!

**Comment by ajparsons** [comment]
This *is* recalculated, but I think it's as column naming problem. Looking around the relevant code: https://github.com/mysociety/caps/blob/8ae60472efcfa9b9421b6fc62d24aa873efa4cd8/caps/management/commands/import_emissions_data.py#L141

The issue might be that the two recalculated columns have the units after them, but the columns specified in `overall_value` do not?

My theory would be taking the units out of line 141 and 142 would fix it.

**Comment by ajparsons** [comment]
I can quickly test that before end of day, but also can I get rid of 'per capita' in the copy while I'm in there? Am generally changing it to 'per person' in blog posts.

**Comment by ajparsons** [comment]
Would also agree dataset is not equivalent units.
