### ISSUE TITLE
Make it clearer when a Scorecard (on CAPE, and Scorecards site) is based on outdated plans/documents

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#387]
Example comment from a council officer:

> Thanks for your email and for linking to the new CAP. It would be great if it would be possible to have a note saying the CAP was published after the final score was awarded. Would that be possible? E.g. Added in March 22, so not included in the final score calculation?

As the Scorecards project receeds further back into the past, this will become more and more of a problem. It’d be good to remove ambiguity here, and provide some recognition for councils who actually _are_ making progress, and publishing new/updated plans.

While we can’t feasibly re-score every new document, it feels like we _could_ make it much clearer when a Scorecard has been based on a now outdated set of documents.

**Comment by JenMysoc** [comment]
I was thinking as the new scorecards ramps up this might need to move up the priority list so we can ensure that people understand that scorecards 1 is out of date and directing them to new scorecards stuff.

**Comment by zarino** [comment]
With [the `scorecards-2023` branch](https://github.com/mysociety/caps/pull/561), this is no longer an issue – the 2022 Plan Scorecards are prominently labelled as a historical archive, so people should _expect_ the Plan scores to be based on old Plans, and the 2023 Action Scorecards aren’t based on Plans at all – meanwhile, https://github.com/mysociety/caps/pull/579 switched CAPE to display the 2023 Action Scorecards scores, instead of 2022 Plan scores, so once that’s deployed this Wednesday (as part of [`scorecards-2023`](https://github.com/mysociety/caps/pull/561)) there’s now less of a disjoint between the council’s latest PlanDocuments in CAPE and the Scorecards scores.
