### ISSUE TITLE
Rename the site (from “Climate Action Plan Explorer“)

### ISSUE THREAD

**Issue by ajparsons** [mysociety/caps#400]
The site has a lot of stuff on it already beyond plans. In future we might add even more.

It might be useful from a branding and conceptual sense to have a new name that reflects this wider purpose.

Something like 'Local Government Climate Dashboard/Radar/Hub'? I mean [not this, but](https://www.youtube.com/watch?v=COCmaZA3d08). 

Relates to discussion in https://github.com/mysociety/caps/issues/225

**Comment by JenMysoc** [comment]
As per our agreement with CE UK we will need to give them notice and they may want to be involved in any name decisions FYI

**Comment by zarino** [comment]
Related: https://github.com/mysociety/caps/issues/212

**Comment by JenMysoc** [comment]
CE UK aren't tied to the name and would be happy to have it renamed - their one note is they would like the term "explorer" in the name somewhere.

One for @MyfanwyNixon when she's back? Or wider mySociety team?

**Comment by MyfanwyNixon** [comment]
Yes I think we should throw it open to the great minds of the wider team - maybe someone will have another shower moment like the one that produced Collideoscope.

That said, I don't think we're going to land on anything too funky if we need to include:
- it's data
- about climate
- regarding local government

Can't do much more than **Local Government Climate Data**

Or can we? Could try AI*.



 *Lol, or maybe not
![image](https://user-images.githubusercontent.com/944656/183447124-06793b4a-5839-4ba7-b44d-a57fc2279966.png)

**Comment by ajparsons** [comment]
In the interests of just going with it, how about CAPE, but we just drop 'Plan' so we're:

`CAPE: Climate Action Explorer`

My main motivation is not liking the domain name, and cape.mysociety.org would be lovely.

**Comment by zarino** [comment]
Renaming the site has again come up as a recommendation in @MyfanwyNixon in #434.

We’ve published a number of things over the last year that mention “CAPE”, so there’s a general feeling that we shouldn’t move away from that unless we have a _really_ good alternative. @crowbot’s opinion was that we could continue using “CAPE” without admitting it’s an acronym at all (see: ARM, ASICS, HSBC, IBM, IKEA, SAP…), and have a tagline that does all the heavy lifting – as @ajparsons has shown above.

In her recommendations doc, @MyfanwyNixon started the ball rolling with this:

> We need something that encapsulates the idea of "Understand what your council, and councils all over the country, are doing to fight climate change." This concept could be conveyed in a strapline even if it's not reflected in the new name.

So, in the spirit of edging the ball forward little by little, here’s just one way that could work in practice, keeping “CAPE” but then letting the strapline do all the heavy lifting:

![Screenshot 2022-11-02 at 12-00-04 Tracking the UK’s journey towards carbon zero](https://user-images.githubusercontent.com/739624/199487958-4d3e293d-e17e-4e82-af54-b2b07f1fad12.png)

@MyfanwyNixon @ajparsons thoughts?

**Comment by ajparsons** [comment]
I like this approach - and also like that quite bold 'CAPE' (mirroring a bold statement of purpose), which feels like it could be used in social images and such.

**Comment by JenMysoc** [comment]
I know you didn't specifically ask me but I like that! It feels like it gets to the point and doesn't mean we have to change everything

**Comment by zarino** [comment]
@MyfanwyNixon any thoughts on the tagline? “Tracking what councils are doing to fight climate change” feels like a bit of a mouthful to me (is it the two -ing words?) but I can’t work out anything simpler. I also wonder whether "tracking" is a bit vague? And does "fight" make it sound too macho?

**Comment by MyfanwyNixon** [comment]
I'm not even sure if 'tracking' properly describes what we're doing on CAPE any more anyway. 

Could we turn it around to what the _user_ is doing (and retain the 'explorer' element we've lost in the title) perhaps? - "Explore what UK councils are doing on climate" or "Explore UK councils' climate action"

**Comment by JenMysoc** [comment]
This one please: _Demanding better action from local councils on climate change_

Especially as we're going to start linking to WTT/TWFY which will cover the demanding angle.

Maybe we can also link out to places like Change.org (searching for climate related petitions for people to sign) or other similar places that help organise collective action (don't know if @sequencefree has thoughts on this) 

Can we agree on the tagline by Monday 14th Nov please so I can put it to CEUK and they then have 2 weeks to agree or disagree

**Comment by sequencefree** [comment]
Quick thought based on a very quick scan of above and not much immersion in related discussion – for this to work for the full breadth of audiences and in particular to mitigate risks around ostracising council actors the tone of this should be kept fairly neutral.

Council might not be doing enough, but does our theory of change suggest that it makes sense for us to be mobilising residents to demand that they do more after 12 years of austerity in a super-centralised democracy?

**Comment by MyfanwyNixon** [comment]
_Informing_ better action on climate change?

**Comment by sequencefree** [comment]
I'm interested in how we may be able to encourage shifts in the modes of councils and residents really.

The frame that underpins the idea of residents demanding action from councils is dependency, which isn't commensurate with the scale of this challenge. And one of the shifts we talk about being necessary is from councils being service providers to conveners. Can we frame CAPE as a means by which both sides step a little closer towards each other, try to understand the constraints and engage constructively on doing what is possible? I don't have enough context about the broader set of changes for the site but that's one thing I like about the idea of integrating public procurement. Users could potentially be helping climate officers to spot opportunities for action early in an area where councils have some actual agency and depending on the user journey they could be helping the council to convene residents around decisions that currently seem to be devoid of democracy with potentially huge climate and other consequences. It's more compelling for me that contacting your Councillors to say something about a plan.

**Comment by JenMysoc** [comment]
> I'm interested in how we may be able to encourage shifts in the modes of action of council actors and residents really.
> 
> The frame that underpins the idea of residents demanding action from councils is dependency, which isn't commensurate with the scale of this challenge. And one of the shifts we talk about being necessary is from councils being service providers to conveners. Can we frame CAPE as a means by which both sides step a little closer towards each other, try to understand the constraints and engage constructively on doing what is possible? I don't have enough context about the broader set of changes for the site but that's one thing I like about the idea of integrating public procurement. Users could potentially be helping climate officers to spot opportunities for action early in an area where councils have some actual agency and depending on the user journey they could be helping the council to convene residents around decisions that currently seem to be devoid of democracy with potentially huge climate and other consequences. It's more compelling for me that contacting your Councillors to say something about a plan.
> 
> 
> This feels like it's going quite deep into the roots of our theory of change – maybe we could discuss?

This does feel like it's a deeper theory of change conversation we need to have and while I agree, I think we also need to be realistic about what is achievable for people with the time and space they have available. Mostly it won't be that deep dive into meeting the council where they are at. And also - it does rely on people feeling like councils do a good job. 

We're in a privileged position where we can see the people and the machine and understand that frankly people _are_ trying to do good things so this doesn't feel like such a stretch...but I think we are the exception rather than the rule. Alex might have some ideas on that when he's not so stretched. 

Also - don't let perfect be the enemy of good enough for now. This won't be the last time this ever gets changed (in fact we _can_ change it every month if we want to ;) ) so as things develop and we get a bit more time and love to put into CAPE lets revisit this and do some deep thinking...but for now, what's good enough as a small step?

**Comment by ajparsons** [comment]
Zarino's original one seemed good enough to me. We can always tweak.

**Comment by ajparsons** [comment]
Like less words, don't want to fight about fighting, but don't think "council climate action" is self-explanatory (in the sense that *we* know what we mean, but it's a bit jargon-y and we're used to it). Want 'climate change' in there because I'm not convinced 'climate' is understood in the same way.

"Tracking what UK councils are doing to fight climate change" < explains what the site does without new terms (and I do like that both us and councils are then doing something *active* in term of sentence-feel. 

So, alternative: 

"Tracking what local councils are doing about climate change."

**Comment by JenMysoc** [comment]
Ok options are:
Tracking what local councils are doing about climate change
or
Informing better action on climate change

**Comment by MyfanwyNixon** [comment]
From the two above, I like _Informing better action on climate change_ for being more succinct, and for encapsulating both the council and the citizen point of view.

Just looked again at [this doc](https://docs.google.com/document/d/12WZob0F9Xsfi4H_y23097Scek0RRUqab8kUPWpXsRwo/edit#heading=h.nw1a5zmwz788) where we also had the concept:

>Your council's committed to do what it takes to fight the climate crisis - now how's it going to get there?

Probably too long!

**Comment by sequencefree** [comment]
I'd lean towards

> Tracking what local councils are doing about climate change

But I'd lose the "local" because it's implied by "councils".

The other option isn't as self-explanatory and is harder to stand up. Can we demonstrate that better action on climate change _is_ happening as a result of CAPE? Most use I've come across involves 3rd parties using CAPE to segment or target councils based on their ambition/action gap (e.g. net zero by 2030 and no plan) to pressure them or promote a solution. But I don't know if any of that activity has led to action, and it begs the question of what we mean by better.

**Comment by ajparsons** [comment]
I like local for sentence-feel (double word local councils and double word climate climate) - but not going to strongly defend it. 

Zarino's original had UK councils, which makes me happy and is conveying separate information:

> Tracking what UK councils are doing about climate change

Either way - broadly this one!

**Comment by JenMysoc** [comment]
CE UK's votes are more for Informing (they like _Informing local action on climate change_ ) because they're worried that tracking sounds too similar to the scorecards. 

I like informing as it also has the implication that we're not just informing citizens, we're informing policy of local councils by sharing best practice and that's definitely where we want to sit

**Comment by ajparsons** [comment]
In the interests of having a decision, cool. Let's get that on with that.
