### ISSUE TITLE
"How to Use" pages for CAPE

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/caps#408]
start with our action plan for outreach and use for CAPE, and then create the pages (or refine existing resources) to fit that

We need to consider:

- what pages we need
- where they link from

Once we know who we're targeting and what they might need:
- [ ] Make a list of pages to create
- [ ] Write copy for pages
- [ ] Add to site

**Comment by ajparsons** [comment]
Relates to (But is not completely the same as) https://github.com/mysociety/caps/issues/434
