### ISSUE TITLE
Revisit CAPE metrics – one year of data, what can we learn?

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/caps#417]
Would be good to set aside some time in April 2022 to go over the automated CAPE metrics reports:

What can we learn about the performance of CAPE, that might influence what features we invest more time in, or which audiences we focus on?
What aren‘t we measuring that we should be?

**Comment by JenMysoc** [comment]
Having gone through the metrics:

We're measuring all we need to measure for our targets. We're looking at new groups of people to outreach to so we need to add a survey option for this (journalists being main one). 

We know council staff are using the site to look up other climatte action plans to make their own or make tweaks or just compare so we should definitely share the site with our comEval list @MyfanwyNixon / @sequencefree (and let annie and isaac know)

Would be good to learn:

- did people wish there had been something to tell them what to _do_ with the information (if they were looking as general interest not work related)
- would people be interested in learning about for example council procurement data if we added that in per council, and if so would they want it to be something they would have tips on how to use that information
- If theres anything they were looking for that we didn't have

**Comment by MyfanwyNixon** [comment]
> We know council staff are using the site to look up other climatte action plans to make their own or make tweaks or just compare so we should definitely share the site with our comEval list @MyfanwyNixon / @sequencefree (and let annie and isaac know)
> 
That's easy enough and I'm happy to put the messaging together. I think we're in agreement that it's fine to import them into Mailchimp for this purpose. 

If so I'll need the spreadsheet/csv of the contacts, and as it's presumably a substantial number of contacts we may see our subscription rate rise (I'll have to check what the next price raise milestone is).

I am tempted to add them as a subsection of the existing Climate list, which would mean they received updates on new features etc. Can anyone see a downside with this? Of course, Mailchimp handles unsubscribes. 

I have pencilled in this Thursday for a climate newsletter, but to avoid them receiving two emails in quick succession we could exclude them from this mailout, either by adding them afterwards or by selecting them as a segment not to receive it.

**Comment by MyfanwyNixon** [comment]
Actually, having now moved on to surveying CEUK's [email list protocol](https://docs.google.com/document/d/1RjQrU-jYyQLFvV_zP5y2kgCIbf0kNFf6xaptB9-d1o8/edit) I realise that this course of action goes against some of what is proposed there.

- _The Climate Officer Email List should not be overused and only used for key events/core services - rather than used for General Update emails_. - indicates that they should **not** be added to the general Climate updates list.
- _Each organisation, mySociety and CEUK, should notify the other in advance when an email to the Climate Officer Email List is planned_ [...] _The aim for the notification of an email being sent should be a month in advance._ - indicates that this should not be done immediately!

**Comment by ajparsons** [comment]
"I think we're in agreement that it's fine to import them into Mailchimp for this purpose." < I'm not! We can use the messages but not use mailchimp. 

https://github.com/mysociety/climate-project/issues/20

**Comment by MyfanwyNixon** [comment]
Ah thank you!

**Comment by ajparsons** [comment]
Still need to have a discussion on this - but sprint metrics have been updated to a new form that should be easier to work with.

**Comment by ajparsons** [comment]
Write up of analytics as part of QCF reporting process: https://docs.google.com/document/d/1RxcmPzN_4KMTFKYuTzYH8jl7VqrU_vHVSlLORD8L6s4/edit#heading=h.pf8dtvkoaxqd
