### ISSUE TITLE
Council Page: New layout

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/caps#420]
The possibility that maybe these CAPE council pages have become too busy, and we could split them up into more distinct sections, or even separate sub-pages. I’m not sure what that would look like, and whether it’d help with the busyness … but if you have some time spare and fancy thinking about potential changes there, that’d be cool too. I don’t want to hold up other, incremental fixes though (like the one above) – just feels sensible to be keeping an eye on the future, alongside the present-day fixes,

**Comment by lucascumsille** [comment]
@lucascumsillemontesinos1 I had a comment from Siôn today, that the council comparisons and "search within the plans of councils similar to this one" feature are probably our unique selling points, so we should display these prominently somewhere.

**Comment by lucascumsille** [comment]
@lucascumsille Add screenshots of the wireframe

**Comment by lucascumsille** [comment]
### Screenshots

### Summary Page
@zarino I remembered you mentioned that for the summary, you wanted to keep discussing about the scorecard component. 

![Image](https://user-images.githubusercontent.com/13790153/187415969-6eda1da8-164e-443e-b07b-956b59cf9e73.png)

### Declaration and pledges
![Image](https://user-images.githubusercontent.com/13790153/187415971-f0b17e87-77ac-4a49-8e7e-6dbe06391402.png)

### Climate plan scorecards
![Image](https://user-images.githubusercontent.com/13790153/187415972-8aab0213-e64e-4371-b365-45b3437d63c6.png)

### Climate Documents
![Image](https://user-images.githubusercontent.com/13790153/187415974-6ad960e0-8631-4c4b-b53c-6d06c010f9ec.png)

### Similar councils
![Image](https://user-images.githubusercontent.com/13790153/187415973-440709cf-2741-47fe-875b-ad2ff6819853.png)

### Emission data
![Image](https://user-images.githubusercontent.com/13790153/187415975-ed9a5ac7-1741-4d9a-af36-e1a8f933763d.png)

### Power and responsibilities
![Image](https://user-images.githubusercontent.com/13790153/187415970-6d467526-3a1e-4c59-b9cd-97f0f05fb384.png)

**Comment by lucascumsille** [comment]
@zarino do you want me to work on this ticket on this sprint or do we need Struan?

**Comment by lucascumsille** [comment]
First work on the subpage navigation and then jump to the subpages.

**Comment by lucascumsille** [comment]
Current branch: 420-council-page-layout
Just in case, @zarino I'll be working on this ticket.

**Comment by zarino** [comment]
@lucascumsille great! I’m still not sure about the the mockups above, but I feel like we need to just see at least _some_ version of this, in order to work out what feels right or not 👍

**Comment by lucascumsille** [comment]
No probs, At this stage I'm working on the functionality and also reusing the the navigation in the about page. I remember we talked about the mockups a few months ago, I think the plan was to reuse as much as we can and avoid creating new components. Unless something has changed.
Also I'll create a content navbar for mobile that can be reuse in both pages, council and about page.

**Comment by zarino** [comment]
@lucascumsille yeah, I think the more we can keep to [existing Bootstrap 4.5 components](https://getbootstrap.com/docs/4.5/getting-started/introduction/) (customised, where necessary, via the [Sass variables](https://getbootstrap.com/docs/4.5/getting-started/theming/#sass-options)) or other components we’ve already created, the simpler this stuff will be to maintain in future, and the more consistent it’ll feel.

**Comment by lucascumsille** [comment]
Some questions:

- Should we change the order of topics, so climate documents seats above the scorecards? For me it's seems the documents are closer to the website main topic than the scorecards, besides the scorecards was originated from the plans?

**Comment by zarino** [comment]
We put the Scorecards higher up the page because 1) at the time, they were new and therefore more interesting; and 2) they were intended as a way to "summarise" a council’s plans – we felt, to a typical user, the list of documents is pretty impenetrable, how are you meant to use and understand those documents? The Scorecards, in contrast, were a really easy way to say "aha, so this council’s plans are good/bad/whatever", hence we put them higher up the page.

Of course, we could change that now.

**Comment by emilyk383** [comment]
Is this 'to do' this sprint or might 'rolling' be a better description?

**Comment by ajparsons** [comment]
Sprint update: I've had a pass adding more handholding content. Currently with @zarino.
