### ISSUE TITLE
[Scorecards] highlight that political control is at time of scoring

### ISSUE THREAD

**Issue by struan** [mysociety/caps#425]
The data on political control of a council is at the time of scoring so we need to highlight this in the filtering, and probably in the FAQ/help page too, to prevent people getting confused for council's that have since changed control.

(scoring was January 2022).

**Comment by zarino** [comment]
Simplest fix for this, I think, would be rewording the "Current political control" label here, to "Political control (Jan 2022)"?

<img width="572" alt="Screenshot 2022-09-23 at 17 06 37" src="https://user-images.githubusercontent.com/739624/192004705-0494efb5-df69-4ded-8568-0c4f6408c66c.png">
