### ISSUE TITLE
[Scorecards] 2023 “teaser” front page with methodology

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#431]
CEUK are hoping to do some comms around the 2023 methodology, in early December 2022.

Replace current homepage with 2023 methodology – "We’re working on 2023 scorecards, here’s how we’re scoring – looking for your council’s 2022 scores, go here."

Move current homepage content to `/scoring/single-tier`.

Have preliminary design work ready by 4th November, so we can put in latest version of methodology content in week commencing 7th November. Full launch currently scheduled for early December.

CEUK happy for this work to be done in a branch on the public repo – they’ve already shared drafts and subsets of the methodology with trusted partners, and by the time they share the latest draft with us, it’ll be almost in final form.

**Comment by zarino** [comment]
Spec for the 2023 methodology page:

- ~90 “data points” (questions), split into 7 sections (like "Buildings & Heating", "Transport", etc)
- Need to display the following about each data point:
   - Question text
   - Short descriptive text, clarifying / explaining the question
   - Whether the question assesses 1) the council’s own operations, or 2) the wider area
   - How this question will be assessed – an existing dataset, FOIs, or research by assessors
   - CEUK’s view on how much this issue contributes to a council’s climate response (high, medium, low)
   - What type(s) of council this question applies to (single tier—and if so, which country/countries?—district, county, NI council, combined authority)
- We need to make it easy for council officers to see only the questions that will apply to their council. We could do this by either:
   - Allowing them to filter by council type (and country)
   - Allowing them to input/select their council name, to show only questions that match that council’s details
- There will also be ~7 additional "pages" of information, FAQs, to accompany the table of questions. May be able to link off to these in Google Docs, or might need to create Django pages for all of them – TBC.

**Comment by lucascumsille** [comment]
INTERNAL

- [ ] Make a accessible table "section weighting"
- [ ] Make a accessible table "How will be marked"

**Comment by lucascumsille** [comment]
@zarino I have created a new branch. I added two fixes that Isaac asked me to edit.
`methodology2023-v2`

**Comment by zarino** [comment]
Done!
