### ISSUE TITLE
[Scorecards] Replace Mailpoet newsletter link with Action network link

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/caps#471]
On the Current [scorecards](https://councilclimatescorecards.uk/) site CE UK have a newsletter sign up link in the footer

<img width="1395" alt="Screenshot 2023-01-12 at 12 29 30" src="https://user-images.githubusercontent.com/4170351/212068282-f3a90e0c-e088-4c4a-b2ca-9bf221cb03b4.png">

This currently links to Mailpoet

<img width="1406" alt="Screenshot 2023-01-12 at 12 29 53" src="https://user-images.githubusercontent.com/4170351/212068350-75d61bf0-3f04-4f65-82ce-75d4c53050ea.png">

But should link to Action Network

https://actionnetwork.org/forms/sign-up-to-our-newsletter-9?source=direct_link& 

they have also shared some Embed code if we prefer:

<link href='https://actionnetwork.org/css/style-embed-v3.css' rel='stylesheet' type='text/css' /><script src='https://actionnetwork.org/widgets/v5/form/sign-up-to-our-newsletter-9?format=js&source=widget'></script><div id='can-form-area-sign-up-to-our-newsletter-9' style='width: 100%'></div>

**Comment by zarino** [comment]
Draft pull request here: https://github.com/mysociety/caps/pull/475

**Comment by JenMysoc** [comment]
This looks like it's still a WiP - how can we get this moved to done?

**Comment by zarino** [comment]
Sorry, yes, this stalled as I was getting a "network error" any time I tried to submit the form – both on my local site, and on the live CEUK site. I didn’t have time to investigate properly.

**Comment by JenMysoc** [comment]
Ok if you don't have time to investigate (fair enough) can we assign this to someone else who could investigate and fix this week?

**Comment by zarino** [comment]
Weirdly, when it checked this morning, it was all working again. 🤔 

Anyway, have forwarded https://github.com/mysociety/caps/pull/475 to Hannah, to check they’re happy with how it looks, before we merge and deploy.
