### ISSUE TITLE
[Scorecards] Add Combined Authority information to Methodology page

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/caps#480]
A few changes to the [2023 draft methodology page](https://councilclimatescorecards.uk/methodology/)

- Addition of Combined Authority info, including link to blog post about CA powers and section weightings (note: CAs have _different sections_ to the other council types)
- Addition of "all the questions" spreadsheet link
- Other minor fixes (typos and a few clarifications)

Final content should be ready for us to use by 20th/21st February, and we’ll need to have this live by 27th Feb.

Full details: https://mysociety.slack.com/archives/CHL40EKB9/p1675846802633599

**Comment by lucascumsille** [comment]
Branch: scorecards-ca-methodology

**Comment by lucascumsille** [comment]
Branch: scorecards-ca-tidy-up

**Comment by JenMysoc** [comment]
Can we close this?

**Comment by lucascumsille** [comment]
Hi @JenMysoc yep it's all good now.
