### ISSUE TITLE
Update for 2023 Councils

### ISSUE THREAD

**Issue by ajparsons** [mysociety/caps#492]
[Four new councils](https://lite.datasette.io/?url=https://pages.mysociety.org/uk_local_authority_names_and_codes/data/uk_la_future/latest/uk_la_future.sqlite#/uk_la_future/uk_local_authorities_future?_filter_column_1=start-date&_filter_op_1=exact&_filter_value_1=2023-04-01&_filter_column=&_filter_op=exact&_filter_value=&_sort=start-date&_sort_by_desc=on) are being created in April 2023, to replace [20 existing councils](https://lite.datasette.io/?url=https://pages.mysociety.org/uk_local_authority_names_and_codes/data/uk_la_future/latest/uk_la_future.sqlite#/uk_la_future/uk_local_authorities_future?_filter_column=end-date&_filter_op=exact&_filter_value=2023-04-01&_sort=end-date&_sort_by_desc=on).

Underlying data preparation:

- [x] Check CAPE imports are version locked for the following datasets.
- [x] Ensure all required columns are in GovLayers
- [x] Update emissions dataset
- [x] Update deprivation dataset
- [x] Update rurality dataset
- [x] Update distance calculations

Website preparation:

- [x] Import data about councils being replaced into CAPE data structure.
- [x] Add content for former councils referring to current councils.
- [x] Add content for new councils explaining why there's nothing there and linking to old ones.

**Comment by zarino** [comment]
On the new council pages, I’m imagining a fairly prominent box that says something like:

> **This council was formed in [date] by the merging of [number] existing councils**
>
> While we wait for new data about this council, you might want to check out the plans and details of the councils it replaced:
> 
> …

And then lists the replaced councils, with some key information about each, like whether they declared a climate emergency, whether they have any plans/documents, and what their overall 2022 Scorecards score was.

Then on each of the replaced council’s pages:

> **This council was replaced by [new council name] on [date]:**
> 
> …

Followed by the same summary information, but just about the _one_ new (replacement) council.

I _had_ wondered whether an equivalent to the existing [two-tier disambiguation page](https://github.com/mysociety/caps/blob/f3de540a329e746f5a14815c4d5b4c9c0c9a09bc/caps/templates/caps/location_results.html)—but showing both the new and old matching councils for the given postcode—might also help. But maybe, with the changes to the individual council pages, it’s not really required?

**Comment by ajparsons** [comment]
Struan is reviewing parts of this, but in principle we'll have something ready to go early April. Some refactoring may be needed depending what has or hasn't been merged by that point.
