### ISSUE TITLE
Buy updated Journolink contacts for Action Scorecards launch

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#509]
Same as we did last time – 1 list of environment journalists, 1 list for local government and 1 list for all regional.

Want to get an update right before we need to announce the new Scorecards.

https://journolink.com

**Comment by zarino** [comment]
This will be happening the week of 21st August, once @MyfanwyNixon is back from annual leave.

**Comment by MyfanwyNixon** [comment]
Have made the enquiry.

**Comment by emilyk383** [comment]
Received by Myf
