### ISSUE TITLE
Implement distinctive branding between 2021 Plan Scorecards and 2023 Action Scorecards

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#511]
- Distinctive branding between the two years
- Some sort of navigation menu structure, to switch between them

Design brief doc says:

> General note about branding – we want to make it very clear that the 2022 Plan Scorecards and the 2023 Action Scorecards are very different things. We should try to use branding to reinforce this – perhaps a different colour scheme between the two years? Different logo?
>
> The nav should make this split between the two years clear too.

**Comment by zarino** [comment]
@lucascumsille as part of this, we should probably discuss whether we want to split out an entirely different Sass pipeline for the 2023 pages (leaving the 2022 styles unchanged), or whether we want to extend the 2022 styles with the new stuff that’s required for 2023.

(I’m just thinking, with an eye on future versions of the Scorecards – the 2022 site was built on Bootstrap 4, which [is now no longer updated](https://github.com/twbs/release), we are likely going to want to switch to Bootstrap 5 at some point, to avoid a repeat of the Foundation situation in TWFY/Alaveteli. Do we switch _this year_, given that this is the first year of the "Action Scorecards", and future years will be very similar? Or do we wait it out?)

**Comment by lucascumsille** [comment]
@zarino I think we can do it, I'm not sure how much impact that will have in the ability to reuse what we already have, but considering there will be a rebranding I think this give us the perfect excuse to upgrade.

**Comment by lucascumsille** [comment]
> Some sort of navigation menu structure, to switch between them

I know we have talked about it. I remember that TWFY navbar came out as an initial idea. What do you think?

**Comment by zarino** [comment]
Some ideas here: https://www.figma.com/file/lQWMFK98xjP7TIGK7PN6fL/2023-Scorecards-nav-ideas

**Comment by lucascumsille** [comment]
- [ ] Color Scheme
- [ ] Navbar
- [ ] Navbar compatibility between V1 and V2

**Comment by lucascumsille** [comment]
After meeting CEUK 21/08/2023

- [ ] Add label to search bar on navigation bar: something like: see your council detailed info.
- [ ] In the Homepage add a third item accordion. This one should include the search bar that takes you to the council.
- [ ] Not design: Ideally we want the search bar at the top to take to the user to the relevant council year.
- [ ] Colour. A few ideas: Let's keep using pastels, what about purple. The current green looks similar to the green party.
- [ ] Can we add a graphic on the hero section or a sticker to show the version of the scorecards.

**Comment by lucascumsille** [comment]
On mobile I ended up hiding the search bar, because it does use a lot of space and looks quite busy.


![Image](https://github.com/mysociety/caps/assets/13790153/722e7c5e-79d1-472f-982d-b6ba6ddd64c4)


![Image](https://github.com/mysociety/caps/assets/13790153/c2596602-ca80-459f-b451-be61e68cef8c)

**Comment by lucascumsille** [comment]
@zarino do we want to continue having the section titles in the table as links. Apparently they were never use and now we have the accordion therefore, I think there is no need to have them.

**Comment by zarino** [comment]
I think we can consider this ticket "done" – the new styling is all in the `scorecards-2023` branch.
