### ISSUE TITLE
Tweaks to 2023 Scorecards homepage / “scoring” table pages 

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#513]
- Table column headers should link to the new section pages rather than the methodology page.
- Remove the “See a council’s Scorecard in more detail” green box above the table.
- Add a “View scores by section” menu somewhere (perhaps in place of the green box?) that lists the sections, and links to the section pages.
- `<link rel=”canonical” href=”https://councilclimatescorecards.uk”>` on `/scoring/<council-type>/` pages.

TBC:

- More explanatory content from CEUK.

**Comment by lucascumsille** [comment]
- [ ] Table Desktop version
- [ ] Table Mobile Version
- [ ] Start with table Bootstrap 5 from scratch and see how complex that will be, otherwise use 2021 tables.
- [ ] Add a “View scores by section” (Not sure if it's needed)

**Comment by emilyk383** [comment]
- [ ] update 'political control' filter to reflect May 2023 election results linked to #516
