### ISSUE TITLE
Move 2022 Plan Scorecards to subdirectory

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#514]
The 2022 Plan Scorecards pages should all move to:

- `/plan-scorecards-2022/`
- `/plan-scorecards-2022/scoring/<council-type>/`
- `/plan-scorecards-2022/council/<council-name>/`
- `/plan-scorecards-2022/questions/<question-slug>/`
- `/plan-scorecards-2022/methodology/` (note, the 2022 methodology, _not_ the 2023 draft!)
- `/plan-scorecards-2022/how-to-use-the-scorecards/`
- `/plan-scorecards-2022/about/`
- `/plan-scorecards-2022/contact/`

Also, a few tweaks to be made to the top of the 2022 homepage and “scoring” table pages:

- Remove Yellow “Now available: Council Climate Action Scorecards draft methodology” banner.
- Add something that makes it _really clear_ you’re looking at the outdated / frozen-in-time 2022 site, and that the more up-to-date 2023 site is a click away.

**Comment by lucascumsille** [comment]
> Add something that makes it really clear you’re looking at the outdated / frozen-in-time 2022 site, and that the more up-to-date 2023 site is a click away.

Initial ideas:

- Subnav banner advising the user.
- Change the BG navcolour between old VS new scorecards.

**Comment by lucascumsille** [comment]
Note to self: Add the switch to the 2021 version
