### ISSUE TITLE
Section pages for 2023 Scorecards

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#516]
The 2023 Action Scorecards will have “section” pages instead of last year’s “question” pages.

The URL structure will be `/section/<section-slug>/`.

At the top of the page, there’ll be some content about the section, why it’s important. CEUK want to add some content that makes the page seem inviting, maybe some headline stats about the section?

This may also include a "Key definitions" list, with definitions of terms like "score" and "weighting", with a link to the Methodology for more info.

Then there’ll a way to pick a council type (five buttons), or automatically pick a council type by searching for the council name (see current [draft Methodology page](https://councilclimatescorecards.uk/methodology/) filters for example of how this will work).

Then there’ll be a table of questions in this section, with a row per question and columns for: question text (with a link to show criteria), question weighting, average score for this council type, score for this council (with link to show evidence, eg: direct to PDF on council site or request on WDTK), score for a chosen comparison council (with link to show evidence).

**Note** that Combined Authority marks are grouped in different sections to the other council types (see table below). So, when switching council type on the section page, we’ll need to handle that, updating the wording of the section title slightly, where required. The aim should be to treat Combined Authorities as consistently as possible with the other council types.

<table>
    <thead><tr>
        <th>Single tier / district / county / NI sections</th>
        <th>Equivalent Combined Authority sections</th>
    </tr></thead>
    <tr>
        <td>Buildings &amp; Heating</td>
        <td>Buildings, Heating &amp; Green Skills</td>
    </tr>
    <tr>
        <td>Transport</td>
        <td>Transport</td>
    </tr>
    <tr>
        <td>Planning &amp; Land Use</td>
        <td rowspan="2">Planning, Biodiversity &amp; Land Use</td>
    </tr>
    <tr>
        <td>Biodiversity</td>
    </tr>
    <tr>
        <td>Governance &amp; Finance</td>
        <td>Governance &amp; Finance</td>
    </tr>
    <tr>
        <td>Collaboration &amp; Engagement</td>
        <td>Collaboration &amp; Engagement</td>
    </tr>
    <tr>
        <td>Waste Reduction &amp; Food</td>
        <td></td>
    </tr>
</table>

**Comment by lucascumsille** [comment]
Important: Being able to search your council and display the scores, also allow to compare with councils(we need to double check with CEUK). 

Probably we will need to have the filter component higher up in the page.

**Comment by emilyk383** [comment]
- [ ] update 'political control' filter to reflect May 2023 election results linked to #513

**Comment by lucascumsille** [comment]
- [ ] At the top of the page, there’ll be some content about the section, why it’s important. CEUK want to add some content that makes the page seem inviting, maybe some headline stats about the section?

- [ ] This may also include a "Key definitions" list, with definitions of terms like "score" and "weighting", with a link to the Methodology for more info.

- [ ] Then there’ll a way to pick a council type (five buttons), or automatically pick a council type by searching for the council name (see current [draft Methodology page](https://councilclimatescorecards.uk/methodology/) filters for example of how this will work).

- [ ] Then there’ll be a table of questions in this section, with a row per question and columns for: question text (with a link to show criteria), question weighting, average score for this council type, score for this council (with link to show evidence, eg: direct to PDF on council site or request on WDTK), score for a chosen comparison council (with link to show evidence).

- [ ] Note that Combined Authority marks are grouped in different sections to the other council types (see table below). So, when switching council type on the section page, we’ll need to handle that, updating the wording of the section title slightly, where required. The aim should be to treat Combined Authorities as consistently as possible with the other council types.
