### ISSUE TITLE
Social media / Open Graph graphics for Scorecards pages

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#517]
At the very least, we’ll want an updated Open Graph image with the [new Action Scorecards branding](https://github.com/mysociety/caps/issues/511). Last time round, we used the same image on all pages of the site, including the council pages.

But it would also be good to investigate the possibility of…

### 1. Individualised Open Graph image for each council page

Could show the council’s name, overall score, and even whether they were a "top scorer" (or whatever) amongst councils of their type. Our research repo does this already, eg: [creating a custom OpenGraph image when you link to a paragraph of text](https://research.mysociety.org/html/prototyping-rental-energy/l/1.4.ar58g.3a4x6.c94ps.k7-d-.html). (The research site generates these images _in advance_, using Selenium to take screenshots of a webpage, [as Github does](https://github.blog/2021-06-22-framework-building-open-graph-images/). We could potentially use something like https://github.com/simonw/shot-scraper for this too.)

### 2. Different Open Graph image for each section page

Could show the section name, and maybe the top few scorers … but which council type? (We could swap the Open Graph image when the user switches between council types on the section page.)

### 3. Fully DIY "generate and download your own Open Graph image" feature

CEUK point to https://www.greennewdealuk.org/campaigns/green-jobs-take-action/ as an example – where you pick your council from a list, and pre-populates an image (via JavaScript Canvas API) that you can download and share.

Ultimately, this is the same as Option 1, except with the addition that the image is available to download, rather than just being hidden in the Open Graph tags.

### 4. Custom infographics for CEUK to share manually, on social media

CEUK point to https://cleancitiescampaign.org/ranking-2022-edition/ (scroll down to "Infographics" section) as an example. I guess we could do this. Would need to take a steer from CEUK on what points they want to draw out from the data. So far, they’ve suggested "X council type do better, or councils in X region do better, or X section scores better by X council types/regions".

**Comment by zarino** [comment]
Have discussed this with @lucascumsille. I think we have two options:

## Option A

@lucascumsille hand-generates a selection of social sharing images, as he did last year. We’d probably change the branding/styling a bit from last year, so it’d probably take about as long as it did last time – around 2 days to settle on the design/layout (with feedback from mySoc and CEUK) and then about a day to churn out all the variations. So 3 days total.

As we did last year, we’d probably have a few "generic" images (not specific to any given council/section) and then customised images for the top scoring councils (showing the council’s name, score, etc) and/or for sections (showing the names and scores of the top scoring councils in the section).

## Option B

We create two HTML+CSS based layouts (one for a council, one for a section) that take data straight from the database, and then use something like https://github.com/simonw/shot-scraper to load and screenshot all of those pages automatically. The archive of all images can then be used for manual social sharing, as well as URLs for OpenGraph tags in each page.

We estimate this would probably take about the same time as Option A (2 days for the design, 1 day for the development of the screenshotter) – maybe slightly less.

The up-side with this option is that we’d get images for _every_ council and _every_ section, could easily re-generate images if any scores change late in the process (unlikely), and could re-use all of the code next time we do the Scorecards.

**Comment by zarino** [comment]
CEUK are happy with Option B. And I think it’s my preferred option too.

**Comment by zarino** [comment]
I’ve made a start on this in https://github.com/mysociety/caps/pull/559

**Comment by lucascumsille** [comment]
@zarino Some notes from today's meeting

Council graph:
- [ ] Change copy from "Worst section" to "Lowest scoring section"
- [ ] Change copy from "Worst section" to "Highest scoring section"
- [ ] Ideally, once we generate the councils' graph(386 I think) we need to split them between types of council and, ideally, in each one of them, split them by region. 

Overall Top Performers Graph:
- [ ] we need to specify the council type for the top performers for the overall score graph.

Council section top performer graph:(X council is top performer in Biodiversity)
- [ ] a graph will display any council that scores above 80% in a X section.

**Comment by zarino** [comment]
Oops sorry @lucascumsille I missed this question! Yes, please do take over!

**Comment by zarino** [comment]
@struan finished this off! 🎉 ❤️

**Comment by lucascumsille** [comment]
Figma here:

https://www.figma.com/design/QhBlsVfmoGpmOgHLYfw50I/Scorecards?node-id=10-2&t=5rHqxw6WtXEVS3Hr-1
