### ISSUE TITLE
[cape] Add climate assemblies.

### ISSUE THREAD

**Issue by ajparsons** [mysociety/caps#522]
Tentatively for second sprint of June, identify climate assemblies and create new document type to import them.

**Comment by ajparsons** [comment]
Still would like to get an afternoon in the current fallow sprint to get an MVP into a PR

**Comment by ajparsons** [comment]
Progress: have a dataset of assemblies that need extra information extracted.

**Comment by emilyk383** [comment]
Are you likely to progress this, this cycle Alex?

**Comment by emilyk383** [comment]
Thanks Alex, I'll ping into next cycle if that's ok. Let me know if I can help speed anything up?

**Comment by ajparsons** [comment]
Done!
