### ISSUE TITLE
Promote CAPE survey

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/caps#524]
**Next steps**

Share in Slacks:
- [x] Code for All
- [x] CAT
- [x] Collective for Climate Action
- [x] ACT Climate Labs
- [x] Environmental Data Network
- [x] DataKind UK
- [x] Bureau Local
- [x] Climate Justice Coalition
- [x] OS-Climate
- [x] Data Collective
- [x] Open Data Scotland
- [x] Open Data Community
- [x] Civic Hackers
- [x] DIGS
- [x] Cardiff Friends of the Earth
- [x] Digital Charities

Share in:
- [x] Climate WhatsApp group

**Background**

Wondering if there's anywhere obvious on the site we can promote https://survey.alchemer.com/s3/7286747/How-have-you-used-CAPE?

For WDTK and FMS it was a bit easier: they both send out alerts so we could add the link there. With our popup survey invitation already running, this is a difficult request, I'm aware - so bright ideas are welcome.

**Comment by MyfanwyNixon** [comment]
I've shared on our newsletter, a couple of Slacks and asked CE UK to share with their networks. Will put it in the Climate newsletter too.

**Comment by sequencefree** [comment]
> I've shared on our newsletter, a couple of Slacks and asked CE UK to share with their networks. Will put it in the Climate newsletter too.

Thanks Myf! Please can you let me know which Slacks you've shared on so that I don't spam? Ta!

**Comment by MyfanwyNixon** [comment]
Cheers Sion - I've shared it on ACT Climate Labs, Code For All and CAT.

**Comment by MyfanwyNixon** [comment]
One thing I've found useful is to double up the message: 
If you have used CAPE, please spend three minutes telling us about it. If you haven't, why not check it out!
