### ISSUE TITLE
Export scoring data from marking app into new Scorecards site

### ISSUE THREAD

**Issue by struan** [mysociety/caps#526]
I think this is mostly the following:

- [x] Export data from marking app
- [x] Update Scorecards tables to handle new data (possibly a separate task
- [x] Import data into Scorecards

There might also be some clean up of the data and also applying to scores/weighting as part of the export.

**Comment by struan** [comment]
One question I have is if we think we should do this as a two stage process with the marking app exporting raw data and then have an intermediate process do the score calculations, or just do it all in one step. Do you have any preferences @ajparsons?

I think fundamentally though this shouldn't require much change on the scorecards side as we should be able to use the same input format as before, and in fact is simpler as we're not doing individual questions so we can strip out a lot of the code, so only need the overall and section scores data.

**Comment by ajparsons** [comment]
I think I've said at previous points happy with either. Given the marking app is python, it can all be incorporated at the source, which might make sense rather than having a weird middle step? there *will* be multiple exports I imagine, so simplifying that flow is good.

**Comment by struan** [comment]
See https://github.com/mysociety/ceuk-marking/pull/99 for work on the first part of this.

**Comment by struan** [comment]
This is largely done.
