### ISSUE TITLE
data.climateemergency.uk domain problems

### ISSUE THREAD

**Issue by ajparsons** [mysociety/caps#547]
All the images are broken on https://cape.mysociety.org/plans/

because they’re attempting to load https://data.climateemergency.uk/static/caps/img/tag-<whatever>.jpg instead of https://cape.mysociety.org/static/caps/img/tag-good-<whatever>.jpg

Will be fixed if CEUK fix the domain (a good idea!) but also we should probably fix whatever config that is.

**Comment by zarino** [comment]
Just adding more detail:

While data.climateemergency.uk redirects to cape.mysociety.org, deep links do not, resulting in a 404 for URLs like https://data.climateemergency.uk/councils/aberdeen-city-council/, which is not great.

As @sagepe has suggested in Slack, really CEUK should just set a CNAME record of `cape.mysociety.org` on their old domain, and then our servers would handle it all fine, as they’re already configured to respond to requests for both domains.

We can revisit with CEUK once things have calmed down after the Scorecards launch.
