### ISSUE TITLE
Deploy 2023 scorecards

### ISSUE THREAD

**Issue by struan** [mysociety/caps#571]
This is the process I have in mind:

### Pre launch
 - [x] rebase scorecards2023 on to master
 - [x] deploy scorecards2023 to staging site for final checking
 - [x] generate social media graphics

### Day before launch
 - [x] merge scorecards2023 branch to master
 - [x] run data export scripts on GRACE
 - [x] upload data to live site
 
### Evening before launch
 - [x] deploy to live
 - [x] run import script

### Day of launch
 - hopefully nothing

**Comment by zarino** [comment]
Deployed! 🎉
