### ISSUE TITLE
document how to use GRACE

### ISSUE THREAD

**Issue by struan** [mysociety/caps#615]
More from an admin perspective so someone who is not Struan can make use of it.

**Comment by zarino** [comment]
@struan has started documenting the project and architecture in https://github.com/mysociety/ceuk-marking

CE UK has sent @struan a few more questions / things they’d like documented, so he assumes he has about half a day of work left on that.

**Comment by zarino** [comment]
We’re going to consider this "done". @struan will be adding more documentation as he implements new features.
