### ISSUE TITLE
[scorecards] York and North Yorkshire CA should have a score of “0” not “None”

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#636]
In the 2023 Action Scorecards, York and North Yorkshire CA currently shows at [the bottom of the Combined Authorities table](https://councilclimatescorecards.uk/scoring/combined/) as “coming soon” due to “technical issues”. This is incorrect. Scores for this CA won’t be coming soon, because it was formed after the 2023 Action Scorecards cut-off date.

The “coming soon” message is appearing because `council.score == None` rather than `council.score == 0` for `york-and-north-yorkshire-mayoral-combined-authority` (see logic in `home_combined.html`).

**Comment by struan** [comment]
Update the database to add a 0 score.
