### ISSUE TITLE
Missing evidence for Combined Authority active travel schemes question (Transport, Q7)

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#646]
> Data is not currently available to create the criteria for this question. This will be published with the complete methodology when the Scorecard results are published.

<img width="961" alt="Screenshot 2024-04-03 at 11 27 12" src="https://github.com/mysociety/caps/assets/739624/072e7c69-b893-4404-8725-e5400cae3ea1">

**Comment by struan** [comment]
The text isn't in the database because it was, and still is, missing from the spreadsheet the questions were imported from. Awaiting text from CEUK.

**Comment by zarino** [comment]
CEUK provided updated text for this today, and @struan has deployed it! ❤️ 

<img width="551" alt="Screenshot 2024-05-07 at 14 30 34" src="https://github.com/mysociety/caps/assets/739624/8efb8679-bdd2-424a-8ed3-70cb9a06cb7c">
