### ISSUE TITLE
Update data packages link

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/caps#667]
A tiny update to the 'About Us' page and
'How to use the Scorecards' - any mention of the data packages needs to link to this updated link (we've been having 2 parellel sites..ops) - This is the new link - https://climateemergency.uk/council-climate-action-scorecards-data-packages/

**Comment by lucascumsille** [comment]
@zarino  Double checking did you do this? because I can already see the link above in master and the live website.

**Comment by zarino** [comment]
@lucascumsille if you look carefully (it took me a few minutes!) you’ll notice that the domain we’re _currently_ using in these links is `climateemergency.org.uk`, but the domain CEUK wants us to link to is `climateemergency.uk`.

We should probably just do a `climateemergency.org.uk` -> `climateemergency.uk` find and replace across all of the templates.

**Comment by zarino** [comment]
I’ve committed a fix for this, as part of https://github.com/mysociety/caps/pull/666 (which we’ll be merging and deploying in the next few days).
