### ISSUE TITLE
[Scorecards] Add Scorecard timeline graphic to 2025 Methodology page

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#675]
Add the graphic from the homepage, to:

- the “Summary” section (perhaps between “…draft methodology below.” and “Whilst every effort…”?) 
- the top of the “Scoring process” section

On the [2025 Methodology page](https://councilclimatescorecards.uk/methodology/).

**Comment by lucascumsille** [comment]
Close with https://github.com/mysociety/caps/pull/680
