### ISSUE TITLE
[Scorecards] Questions missing for some council types on 2025 Methodology page

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#679]
Isaac reports:

- Biodiversity:
   - Question 1 should apply to Counties, Districts, Single Tiers, and NI councils (currently shown as applying only to NI councils)
   - Question 4 should apply to Single Tier councils in England, and Counties (currently shown as applying only to Counties)
- Transport
   - Question 8b should apply to Single Tier councils in England, and Counties (currently shown as applying only to Counties)

https://councilclimatescorecards.uk/methodology/#section-question-criteria

**Comment by zarino** [comment]
@struan I wonder whether this is related enough to https://github.com/mysociety/caps/issues/668 (since it involves three questions that only apply to _English_ single tiers) that it makes sense to look at them both at the same time?

**Comment by struan** [comment]
Fixed. The issue was the question spreadsheet had unexpected data in the column that includes things in the councils types. I've updated the import script for GRACE to cope with this and then re-imported, exported from GRACE and imported into scorecards.
