### ISSUE TITLE
[Scorecards] Integer numbers instead of float numbers for question marks 

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/caps#699]
Minor issue raised by CEUK, but in some question we have marks that are displayed as float numbers instead of integer, which seems a bit odd when reading the whole table. 

There are questions where using float numbers make sense because they can be eg. 1.25, we wouldn't want to lose that accuracy when it's necessary. Could we add in Django a conditional to only display float numbers if needed and display integer by default?

<img width="1293" alt="Screenshot 2024-10-21 at 11 03 28" src="https://github.com/user-attachments/assets/380faf83-8cd1-4722-9103-bf5c4005babd">

Example extracted from:
https://councilclimatescorecards.uk/councils/london-borough-of-islington/

**Comment by zarino** [comment]
[Django’s `floatformat` filter](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#floatformat) gets us real close here. `{{ 1.0|floatformat }}` outputs `1`, yay!

But if `floatformat` is used on a number with a fraction part, it _will_ truncate or pad the decimals to either the requested number of places, or to the default (which is 1 decimal place). So `{{ 1.25|floatformat }}` will become `1.3`.

Will this be a problem? Can the number of _marks_ a council got on a question ever be a fraction with more than one decimal place? And if it can, do we care if it gets rounded to one decimal place?

Assuming it’s fine, I’ve prepped a PR here with the required changes: #702

**Comment by zarino** [comment]
If we want more decimal places, we can have them. `|floatformat:-2` would display `-0.32` as `-0.32`, but, if there are any other single-character decimals, like `1.2`, say, they’d get displayed as `1.20`.

Is the air quality mark the only one that can be a decimal? (The answer to this may be different last year and this year!)

**Comment by lucascumsille** [comment]
Checking with CEUK if that's the case

**Comment by lucascumsille** [comment]
@zarino there is no certainty from CEUK at least this week. 
Here is what I found checking the current 2023 site(note that this only cover if the council had marks(positive or negative)):

- 2.11 [Has the council approved, expanded or built a high carbon transport project since 2019?](https://councilclimatescorecards.uk/question/s2_tran_q11/?type=single)
- 2.12 [Has the council approved, expanded or built a high carbon transport project since 2019?](https://councilclimatescorecards.uk/question/s2_tran_q11/?type=single)
- 4.12 [Does the council have direct investments in airports or high carbon intensive energy industries?](https://councilclimatescorecards.uk/question/s4_g_f_q12/?type=single)

I wonder if in there is an easy way in the backend to differentiate them from the rest of questions
